Repository passepartoutvpn/tunnelkit, pull requests merged in 2023-12, with the labels that each got.

#348 Convert encryption tests to proper unit tests
  Sources/CTunnelKitCore/ZeroingData.m
  Sources/CTunnelKitOpenVPNProtocol/CryptoCBC.m
  Sources/CTunnelKitOpenVPNProtocol/include/Crypto.h
  Sources/TunnelKitOpenVPNProtocol/ControlChannelSerializer.swift
  Tests/TunnelKitCoreTests/RandomTests.swift
  Tests/TunnelKitCoreTests/RoutingTests.swift
  Tests/TunnelKitLZOTests/CompressionTests.swift
  Tests/TunnelKitOpenVPNTests/AppExtensionTests.swift
  Tests/TunnelKitOpenVPNTests/ConfigurationParserTests.swift
  Tests/TunnelKitOpenVPNTests/ControlChannelTests.swift
  Tests/TunnelKitOpenVPNTests/CryptoAEADTests.swift
  Tests/TunnelKitOpenVPNTests/CryptoCBCTests.swift
  Tests/TunnelKitOpenVPNTests/CryptoCTRTests.swift
  Tests/TunnelKitOpenVPNTests/DataPathEncryptionTests.swift
  Tests/TunnelKitOpenVPNTests/DataPathPerformanceTests.swift
  Tests/TunnelKitOpenVPNTests/EncryptionPerformanceTests.swift
  Tests/TunnelKitOpenVPNTests/EncryptionTests.swift
  Tests/TunnelKitOpenVPNTests/LinkTests.swift
  Tests/TunnelKitOpenVPNTests/PacketTests.swift
  Tests/TunnelKitOpenVPNTests/PushTests.swift
Labels: enhancement

#349 Dangling pointers in crypto tests
  Tests/TunnelKitOpenVPNTests/CryptoAEADTests.swift
  Tests/TunnelKitOpenVPNTests/CryptoCBCTests.swift
  Tests/TunnelKitOpenVPNTests/CryptoCTRTests.swift
  Tests/TunnelKitOpenVPNTests/EncryptionPerformanceTests.swift
  Tests/TunnelKitOpenVPNTests/EncryptionTests.swift
Labels: bug

#347 Upgrade to OpenSSL 3
  CHANGELOG.md
  Package.resolved
  Package.swift
  Sources/CTunnelKitOpenVPNProtocol/CryptoBox.m
  Sources/CTunnelKitOpenVPNProtocol/CryptoCBC.m
  Sources/CTunnelKitOpenVPNProtocol/CryptoCTR.m
  Sources/CTunnelKitOpenVPNProtocol/TLSBox.m
Labels: enhancement, OpenVPN

#350 Drop broken/unused routing table code
  Sources/CTunnelKitCore/RoutingTable.m
  Sources/CTunnelKitCore/RoutingTableEntry.m
  Sources/CTunnelKitCore/include/RoutingTable.h
  Sources/CTunnelKitCore/include/RoutingTableEntry.h
  Sources/CTunnelKitCore/include/route.h
Labels: bug

#341 Add WireGuard RX/TX data statistics
  Demo/Host/ViewController.swift
  Package.swift
  Sources/TunnelKitManager/NetworkExtensionVPN.swift
  Sources/TunnelKitManager/VPNNotification.swift
  Sources/TunnelKitWireGuardAppExtension/WireGuardTunnelProvider.swift
  Sources/TunnelKitWireGuardManager/DataCount+WireGuard.swift
  Sources/TunnelKitWireGuardManager/WireGuard+ProviderConfiguration.swift
Labels: enhancement, WireGuard

#400 Attach user data to VPN configuration
  CHANGELOG.md
  Package.resolved
  Sources/TunnelKitManager/NetworkExtensionConfiguration.swift
  Sources/TunnelKitManager/NetworkExtensionVPN.swift
Labels: enhancement
